package ClientApp;

/**
* ClientApp/ClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientDL.idl
* Sexta-feira, 20 de Janeiro de 2017 13h20min56s GMT-03:00
*/

public final class ClientHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientApp.Client value = null;

  public ClientHolder ()
  {
  }

  public ClientHolder (ClientApp.Client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientApp.ClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientApp.ClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientApp.ClientHelper.type ();
  }

}
