package ClientApp;


/**
* ClientApp/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClientDL.idl
* Sexta-feira, 20 de Janeiro de 2017 13h20min56s GMT-03:00
*/

public interface Client extends ClientOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Client
