package CoordinatorApp;


/**
* CoordinatorApp/CoordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CoordinatorDL.idl
* Sexta-feira, 20 de Janeiro de 2017 14h07min38s GMT-03:00
*/

public interface CoordinatorOperations 
{
  void request (String processID);
  void release (String processID);
} // interface CoordinatorOperations
