package CoordinatorApp;


/**
* CoordinatorApp/Coordinator.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CoordinatorDL.idl
* Sexta-feira, 20 de Janeiro de 2017 14h07min38s GMT-03:00
*/

public interface Coordinator extends CoordinatorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Coordinator
