package CoordinatorApp;

/**
* CoordinatorApp/CoordinatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CoordinatorDL.idl
* Sexta-feira, 20 de Janeiro de 2017 14h07min38s GMT-03:00
*/

public final class CoordinatorHolder implements org.omg.CORBA.portable.Streamable
{
  public CoordinatorApp.Coordinator value = null;

  public CoordinatorHolder ()
  {
  }

  public CoordinatorHolder (CoordinatorApp.Coordinator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CoordinatorApp.CoordinatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CoordinatorApp.CoordinatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CoordinatorApp.CoordinatorHelper.type ();
  }

}
